WoolBoxStudio/Models/Portfolio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WoolBoxStudio.Models
{
    public class Portfolio
    {
        public virtual int PortfolioID { get; set; }
        public virtual int CategoryID { get; set; }

        [Required(ErrorMessage = "A title is required")]
        public virtual string Title { get; set; }

        [Required(ErrorMessage = "A description is required")]
        [DataType(DataType.MultilineText)]
        public virtual string Description { get; set; }

        [Display(Name = "Image")]
        public virtual string ImageLink { get; set; }

        public virtual Category Category { get; set; }
    }
}

WoolBoxStudio/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoolBoxStudio.Filters;
using WoolBoxStudio.Models;
using System.IO;

namespace WoolBoxStudio.Controllers
{
    [InitializeSimpleMembership]
    [Authorize(Roles = "Administrator")]
    public class PortfolioController : Controller
    {
        private WoolBoxStudioContext db = new WoolBoxStudioContext();

        //
        // GET: /Portfolio/

        public ActionResult Index()
        {
            var portfolios = db.Portfolios.Include(p => p.Category);
            return View(portfolios.ToList());
        }

        //
        // GET: /Portfolio/Details/5

        public ActionResult Details(int id = 0)
        {
            Portfolio portfolio = db.Portfolios.Find(id);
            if (portfolio == null)
            {
                return HttpNotFound();
            }
            return View(portfolio);
        }

        //
        // GET: /Portfolio/Create

        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            return View();
        }

        //
        // POST: /Portfolio/Create

        [HttpPost]
        public ActionResult Create(Portfolio portfolio, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/Portfolio/") + file.FileName);
                        portfolio.ImageLink = "../Images/Portfolio/" + file.FileName;
                        db.Portfolios.Add(portfolio);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be a .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Image must be uploaded");
                }
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", portfolio.CategoryID);
            return View(portfolio);
        }

        //
        // GET: /Portfolio/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Portfolio portfolio = db.Portfolios.Find(id);
            if (portfolio == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", portfolio.CategoryID);
            return View(portfolio);
        }

        //
        // POST: /Portfolio/Edit/5

        [HttpPost]
        public ActionResult Edit(Portfolio portfolio, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/Portfolio/") + file.FileName);
                        portfolio.ImageLink = "../Images/Portfolio/" + file.FileName;
                        db.Entry(portfolio).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be a .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Image must be uploaded");
                }
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", portfolio.CategoryID);
            return View(portfolio);
        }

        //
        // GET: /Portfolio/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Portfolio portfolio = db.Portfolios.Find(id);
            if (portfolio == null)
            {
                return HttpNotFound();
            }
            return View(portfolio);
        }

        //
        // POST: /Portfolio/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Portfolio portfolio = db.Portfolios.Find(id);
            db.Portfolios.Remove(portfolio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WoolBoxStudio/Views/Portfolio/Create.cshtml
@model WoolBoxStudio.Models.Portfolio

@{
    ViewBag.Title = "Create Portfolio Item";
}
@Html.Partial("_AdminMenu")
<h2>Create Portfolio Item</h2>

@using (Html.BeginForm("Create", "Portfolio", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)

    <p>   
        @Html.LabelFor(model => model.CategoryID, "Category"):
    </p>
    <p>
        @Html.DropDownList("CategoryID", String.Empty)
        @Html.ValidationMessageFor(model => model.CategoryID)
    </p>
    
    <p>
        @Html.LabelFor(model => model.Title):
    </p>
    <p>
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </p>
    <p>
        @Html.LabelFor(model => model.Description):
    </p>
    <p>
        @Html.EditorFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
    </p>
    <p>
        @Html.LabelFor(model => model.ImageLink):
    </p>
    <p>
        <input id="ImageLink" type="file" name="file" />
        @Html.ValidationMessageFor(model => model.ImageLink)
    </p>
    <input type="submit" value="Create" />

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WoolBoxStudio/Views/Portfolio/Delete.cshtml
@model WoolBoxStudio.Models.Portfolio

@{
    ViewBag.Title = "Delete Portfolio Item";
}
@Html.Partial("_AdminMenu")
<h2>Delete Portfolio Item</h2>

<h3>Are you sure you want to delete this?</h3>
<p>
    @Html.DisplayNameFor(model => model.Category.Name):
    @Html.DisplayFor(model => model.Category.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.Title):
    @Html.DisplayFor(model => model.Title)
</p>
<p>
    @Html.DisplayNameFor(model => model.Description):
    @Html.DisplayFor(model => model.Description)
</p>
<p>
    @Html.DisplayNameFor(model => model.ImageLink):
    @Html.DisplayFor(model => model.ImageLink)
</p>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

WoolBoxStudio/Views/Portfolio/Details.cshtml
@model WoolBoxStudio.Models.Portfolio

@{
    ViewBag.Title = "Portfolio Item Details";
}
@Html.Partial("_AdminMenu")
<h2>Portfolio Item Details</h2>
<p>
    @Html.DisplayNameFor(model => model.Category.Name):
    @Html.DisplayFor(model => model.Category.Name)
</p>
<p>
    @Html.DisplayNameFor(model => model.Title):
    @Html.DisplayFor(model => model.Title)
</p>
<p>
    @Html.DisplayNameFor(model => model.Description):
    @Html.DisplayFor(model => model.Description)
</p>
<p>
    @Html.DisplayNameFor(model => model.ImageLink):
</p>
<p>
    <img src="../@Model.ImageLink" alt="@Model.Title" class="adminDetails"/>
</p>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.PortfolioID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WoolBoxStudio/Views/Portfolio/Edit.cshtml
@model WoolBoxStudio.Models.Portfolio

@{
    ViewBag.Title = "Edit";
}
@Html.Partial("_AdminMenu")
<h2>Edit Portfolio Item</h2>

@using (Html.BeginForm("Edit", "Portfolio", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)


        @Html.HiddenFor(model => model.PortfolioID)

    <p>   
        @Html.LabelFor(model => model.CategoryID, "Category"):
    </p>
    <p>
        @Html.DropDownList("CategoryID", String.Empty)
        @Html.ValidationMessageFor(model => model.CategoryID)
    </p>
    
    <p>
        @Html.LabelFor(model => model.Title):
    </p>
    <p>
        @Html.EditorFor(model => model.Title)
        @Html.ValidationMessageFor(model => model.Title)
    </p>
    <p>
        @Html.LabelFor(model => model.Description):
    </p>
    <p>
        @Html.EditorFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
    </p>
    <p>
        @Html.LabelFor(model => model.ImageLink):
    </p>
    <p>
        <input id="ImageLink" type="file" name="file" />
        @Html.ValidationMessageFor(model => model.ImageLink)
    </p>
    <input type="submit" value="Create" />
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WoolBoxStudio/Views/Portfolio/Index.cshtml
@model IEnumerable<WoolBoxStudio.Models.Portfolio>

@{
    ViewBag.Title = "Portfolio Admin";
}
@Html.Partial("_AdminMenu")
<h2>Portfolio Items</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageLink)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageLink)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PortfolioID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PortfolioID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PortfolioID })
        </td>
    </tr>
}

</table>