WoolBoxStudio/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoolBoxStudio.Filters;
using WoolBoxStudio.Models;

namespace WoolBoxStudio.Controllers
{
    [InitializeSimpleMembership]
    [Authorize(Roles = "Administrator")]
    public class AboutController : Controller
    {
        private WoolBoxStudioContext db = new WoolBoxStudioContext();

        //
        // GET: /About/

        public ActionResult Index()
        {
            return View(db.Abouts.ToList());
        }

        //
        // GET: /About/Details/5

        public ActionResult Details(int id = 0)
        {
            About about = db.Abouts.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        //
        // GET: /About/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /About/Create

        [HttpPost]
        public ActionResult Create(About about, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/About/") + file.FileName);
                        about.ImageLink = "../Images/About/" + file.FileName;
                        db.Abouts.Add(about);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be a .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Image must be uploaded");
                }
            }
            return View(about);
        }

        //
        // GET: /About/Edit/5

        public ActionResult Edit(int id = 0)
        {
            About about = db.Abouts.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        //
        // POST: /About/Edit/5

        [HttpPost]
        public ActionResult Edit(About about, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/") + file.FileName);
                        about.ImageLink = "../Images/About/" + file.FileName;
                        db.Entry(about).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be a .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Image must be uploaded");
                }
            }
            return View(about);
        }

        //
        // GET: /About/Delete/5

        public ActionResult Delete(int id = 0)
        {
            About about = db.Abouts.Find(id);
            if (about == null)
            {
                return HttpNotFound();
            }
            return View(about);
        }

        //
        // POST: /About/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            About about = db.Abouts.Find(id);
            db.Abouts.Remove(about);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WoolBoxStudio/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoolBoxStudio.Filters;

namespace WoolBoxStudio.Controllers
{
    [InitializeSimpleMembership]
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Index()
        {
            return View();
        }

    }
}

WoolBoxStudio/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoolBoxStudio.Filters;
using WoolBoxStudio.Models;

namespace WoolBoxStudio.Controllers
{
    [InitializeSimpleMembership]
    [Authorize(Roles = "Administrator")]
    public class CategoryController : Controller
    {
        private WoolBoxStudioContext db = new WoolBoxStudioContext();

        //
        // GET: /Category/

        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        //
        // GET: /Category/Details/5

        public ActionResult Details(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // GET: /Category/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Category/Create

        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        //
        // GET: /Category/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Category/Edit/5

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        //
        // GET: /Category/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        //
        // POST: /Category/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WoolBoxStudio/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoolBoxStudio.Models;
using WoolBoxStudio.Filters;
using System.IO;
namespace WoolBoxStudio.Controllers
{
    [InitializeSimpleMembership]
    [Authorize(Roles = "Administrator")]
    public class LocationController : Controller
    {
        private WoolBoxStudioContext db = new WoolBoxStudioContext();

        //
        // GET: /Location/

        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        //
        // GET: /Location/Details/5

        public ActionResult Details(int id = 0)
        {
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //
        // GET: /Location/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Location/Create

        [HttpPost]
        public ActionResult Create(Location location, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/") + file.FileName);
                        location.ImageLink = "../Images/" + file.FileName;
                        db.Locations.Add(location);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be a .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Image must be uploaded");
                }
            }
            return View(location);
        }
        //
        // GET: /Location/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //
        // POST: /Location/Edit/5

        [HttpPost]
        public ActionResult Edit(Location location, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpeg", ".jpg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/") + file.FileName);
                        location.ImageLink = "../Images/" + file.FileName;
                        db.Entry(location).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be a .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Image must be uploaded");
                }
            }
            return View(location);
        }
        //
        // GET: /Location/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        //
        // POST: /Location/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WoolBoxStudio/Views/Shared/_AdminMenu.cshtml
<nav id="adminNav">
    <ul>
        <li>@Html.ActionLink("Admin Home", "Index", "Admin")</li>
        <li>@Html.ActionLink("Home Page", "Index", "HomeCarousel")</li>
        <li>@Html.ActionLink("Portfolio", "Index", "Portfolio")</li>
        <li>@Html.ActionLink("Product Categories", "Index", "Category")</li>
        <li>@Html.ActionLink("Craft Shows", "Index", "CraftShow")</li>
        <li>@Html.ActionLink("Retail Locations", "Index", "Location")</li>
        <li>@Html.ActionLink("About Me", "Index", "About")</li>   
    </ul>
</nav>

WoolBoxStudio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href='http://fonts.googleapis.com/css?family=Handlee' rel='stylesheet' type='text/css'>
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/flexslider.css")
        @Scripts.Render("~/bundles/modernizr")

    </head>
    <body>
        <header>
            <div id="headerContent">
                <img src="~/Content/Images/WoolBoxLogo.png" alt="Wool Box Logo" />
                <h1>@Html.ActionLink("Wool Box Studio", "Index", "Home")</h1>
                    <div id="socialMedia">
                        <a href="https://www.facebook.com/woolboxstudio" target="_blank"><img src="~/Content/Images/facebookLogo.png" alt="Facebook Logo" /></a>
                        <a href="http://pinterest.com/stephsims/" target="_blank"><img src="~/Content/Images/pinterestLogo.png" alt="Facebook Logo" /></a>
                    </div>
                    <div id="loginInfo">
                        @Html.Partial("_LoginPartial")
                    </div>

            </div>
        </header>
        <nav id="mainNav">
            <ul>
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Portfolio", "Portfolio", "Home")</li>
                <li><a href="javascript:void(0)">Shop</a>
                    <ul>
                        <li><a href="http://www.etsy.com/shop/WoolBoxStudioStore" target="_blank">Etsy</a></li>
                        <li><a href="http://www.spoonflower.com/profiles/woolboxstudio?sub_action=designs" target="_blank">Spoonflower</a></li>
                        <li><a href="http://www.zazzle.com/woolboxstudioink" target="_blank">Zazzle</a></li>
                        <li><a href="http://www.cafepress.com/woolboxstudioink" target="_blank">Cafe Press</a></li>
                    </ul>
                </li>
                <li>@Html.ActionLink("Craft Shows", "CraftShows", "Home")</li>
                <li>@Html.ActionLink("Locations", "Locations", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                @if (User.IsInRole("Administrator"))
                {
                    <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                }
                
            </ul>
        </nav>
        <div id="body">
            @RenderSection("featured", required: false)
            @RenderBody()
        </div>
        <footer>
            <p>&copy; @DateTime.Now.Year - Wool Box Studio</p>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>