WoolBoxStudio/Models/HomeCarousel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WoolBoxStudio.Models
{
    public class HomeCarousel
    {
        public virtual int HomeCarouselID { get; set; }

        [Required(ErrorMessage = "A description is required")]
        public virtual string Description { get; set; }

        [Display(Name = "Image")]
        public virtual string ImageLink { get; set; }
    }
}

WoolBoxStudio/Controllers/HomeCarouselController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WoolBoxStudio.Filters;
using WoolBoxStudio.Models;


namespace WoolBoxStudio.Controllers
{
    [InitializeSimpleMembership]
    [Authorize(Roles = "Administrator")]
    public class HomeCarouselController : Controller
    {
        private WoolBoxStudioContext db = new WoolBoxStudioContext();

        //
        // GET: /HomeCarousel/

        public ActionResult Index()
        {
            return View(db.HomeCarousels.ToList());
        }

        //
        // GET: /HomeCarousel/Details/5

        public ActionResult Details(int id = 0)
        {
            HomeCarousel homecarousel = db.HomeCarousels.Find(id);
            if (homecarousel == null)
            {
                return HttpNotFound();
            }
            return View(homecarousel);
        }

        //
        // GET: /HomeCarousel/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /HomeCarousel/Create

        [HttpPost]
        public ActionResult Create(HomeCarousel homecarousel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/HomePage/") + file.FileName);
                        homecarousel.ImageLink = "../Images/HomePage/" + file.FileName;
                        db.HomeCarousels.Add(homecarousel);
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be in either .jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Please select an image to upload");
                }
            }
            return View(homecarousel);
        }

        //
        // GET: /HomeCarousel/Edit/5

        public ActionResult Edit(int id = 0)
        {
            HomeCarousel homecarousel = db.HomeCarousels.Find(id);
            if (homecarousel == null)
            {
                return HttpNotFound();
            }
            return View(homecarousel);
        }

        //
        // POST: /HomeCarousel/Edit/5

        [HttpPost]
        public ActionResult Edit(HomeCarousel homecarousel, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string extension = Path.GetExtension(file.FileName);
                    string[] safeExtensions = { ".jpg", ".jpeg", ".png", ".gif" };

                    if (safeExtensions.Contains(extension))
                    {
                        file.SaveAs(HttpContext.Server.MapPath("~/Images/HomePage/") + file.FileName);
                        homecarousel.ImageLink = "../Images/HomePage/" + file.FileName;
                        db.Entry(homecarousel).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("ImageLink", "Image must be in either.jpg, .png, or .gif format");
                    }
                }
                else
                {
                    ModelState.AddModelError("ImageLink", "Please select an image to upload");
                }
            }
            return View(homecarousel);
        }

        //
        // GET: /HomeCarousel/Delete/5

        public ActionResult Delete(int id = 0)
        {
            HomeCarousel homecarousel = db.HomeCarousels.Find(id);
            if (homecarousel == null)
            {
                return HttpNotFound();
            }
            return View(homecarousel);
        }

        //
        // POST: /HomeCarousel/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            HomeCarousel homecarousel = db.HomeCarousels.Find(id);
            db.HomeCarousels.Remove(homecarousel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WoolBoxStudio/Views/HomeCarousel/Create.cshtml
@model WoolBoxStudio.Models.HomeCarousel

@{
    ViewBag.Title = "Create Carousel Item";
}
@Html.Partial("_AdminMenu")
<h2>Create Image Carousel Item</h2>

@using (Html.BeginForm("Create", "HomeCarousel", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    @Html.ValidationSummary(true)

    <p>
        @Html.LabelFor(model => model.Description):
    </p>
    <p>
        @Html.EditorFor(model => model.Description)
        @Html.ValidationMessageFor(model => model.Description)
    </p>
    <p>
        @Html.LabelFor(model => model.ImageLink):
    </p>
    
    <p>
        <input id="ImageLink" type="file" name="file" />
        @Html.ValidationMessageFor(model =>model.ImageLink)
    </p>
    
    <p>
        <input type="submit" value="Create" />
    </p>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    }

WoolBoxStudio/Views/HomeCarousel/Delete.cshtml
@model WoolBoxStudio.Models.HomeCarousel

@{
    ViewBag.Title = "Delete Carousel Item";
}
@Html.Partial("_AdminMenu")

<h2>Delete Image Carousel Item</h2>
<h3>Are you sure you want to delete this?</h3>


<p>
    @Html.DisplayNameFor(model => model.Description)
    @Html.DisplayFor(model => model.Description);
</p>

<p>
    @Html.DisplayNameFor(model => model.ImageLink)
    @Html.DisplayFor(model => model.ImageLink);
</p>

@using (Html.BeginForm()) { 
    <p>
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "Index")
    </p>

}

WoolBoxStudio/Views/HomeCarousel/Details.cshtml
@model WoolBoxStudio.Models.HomeCarousel

@{
    ViewBag.Title = "Image Carousel Details";
}
@Html.Partial("_AdminMenu")

<h2>Image Carousel Details</h2>

<p>
    @Html.DisplayNameFor(model =>model.Description):
    @Html.DisplayFor(model => model.Description)
</p>

<p>
    @Html.DisplayNameFor(model => model.ImageLink):
</p>

<p>
    <img src="../@Model.ImageLink" alt="Model.Title" class="adminDetails" />
</p>

WoolBoxStudio/Views/HomeCarousel/Edit.cshtml
@model WoolBoxStudio.Models.HomeCarousel

@{
    ViewBag.Title = "Edit Image Carousel";
}
@Html.Partial("_AdminMenu")

<h2>Edit Image Carousel Item</h2>

@using (Html.BeginForm("Edit", "HomeCarousel", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    @Html.ValidationSummary(true)

        @Html.HiddenFor(model =>model.HomeCarouselID)

<p>
    @Html.LabelFor(model => model.Description):
</p>
<p>
    @Html.EditorFor(model => model.Description)
    @Html.ValidationMessageFor(model => model.Description)
</p>

<p>
    @Html.LabelFor(model => model.ImageLink):
</p>

<p>
    <input id="ImageLink" type="file" name="file" />
    @Html.ValidationMessageFor(model => model.ImageLink)
</p>

<p>
    <input type="submit" value="Create" />
</p>

}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WoolBoxStudio/Views/HomeCarousel/Index.cshtml
@model IEnumerable<WoolBoxStudio.Models.HomeCarousel>

@{
    ViewBag.Title = "Image Carousel Admin";
}
@Html.Partial("_AdminMenu")
<h2>Edit content for this section below.</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImageLink)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) { 
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ImageLink)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.HomeCarouselID })
            @Html.ActionLink("Details", "Details", new { id=item.HomeCarouselID })
            @Html.ActionLink("Delete", "Delete", new { id=item.HomeCarouselID })
        </td>
    </tr>
}

</table>